workflows:
  ios-workflow:
    name: Edgewallets
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      vars:
        APP_ID: dorcnuel@gmail.com # <-- Put your APP ID here
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Flutter build ipa
        script: | 
          flutter build ios --debug --no-codesign \
            --build-name=1.0.0 \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
   
