 workflows:
  ios-workflow:
    name: Edgewallets
    scripts:
    - name: Set up code signing settings on Xcode project
      script: | 
        xcode-project use-profiles
    - name: Get Flutter packages
      script: | 
        flutter packages pub get
    - name: Install pods
      script: | 
        find . -name "Podfile" -execdir pod install \;
    - name: Flutter build ipa
      script: | 
        flutter build ios --debug --no-codesign
   publishing: 
      email:
        recipients:
          - oluwaleyeolufemi@gmail.com
        notify:
          success: true
          failure: false
    artifacts:
      - build/ios/app/*.app
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      
      
   
