workflows:
    android-app: # workflow ID
        name: Edgewallets # workflow name
        scripts:
            - ./gradlew assembleDebug
        artifacts:
            - build/outputs/**/**/*.apk
            - app/build/**/outputs/**/*.apk
        publishing:
            email:
              recipients:
                - oluwaleyeolufemi@gmail.com # enter your email id here
