workflows:
  my-workflow:
    scripts:
      - name: say hello
        script: echo "Hello Codemagician!"
  my-workflow2:
    scripts:
      - name: Run iOS tests
        script: |
          set -e # exit on first failed command

          xcode-project run-tests \
              --workspace ${XCODE_WORKSPACE?} \
              --scheme ${XCODE_SCHEME?} \
              --device "iPhone 12"
        test_report: ios/test/*.xml
